name: 'learn_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'neil-snowflake-test-db'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]
analysis-paths: ["analyses"]
test-paths: ["tests"]

target-path: "target"  # directory which will house compiled/staged models
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  learn_dbt:
    # Applies to all files under models/example/
    example:
      materialized: view

# Modify this section for the hook
on-run-start:
  - "USE WAREHOUSE transform_wh;"